version: "3"
services:
  node:
    image: slashe/node:1.0.4
    ports:
      - "1000:8080"
    restart: always
  webapp:
    image: slashe/webapp:${SEILA}
    ports:
      - "2000:80"
    restart: always