version: "3"
services:
  nginx:
    image: slashe/nginx:1.0.1
    ports:
      - "3000:80"
  node:
    image: slashe/node:1.0.4
    ports:
      - "1000:80"
    restart: always
  webapp:
    image: slashe/webapp:${SEILA}
    ports:
      - "2000:80"
    restart: always