version: "3"
services:
  nginx:
    build: ./nginx
    image: slashe/nginx
    ports:
      - "80:80"
  node:
    build: ./node
    image: slashe/node
    ports:
      - "2000:80"
    restart: always
  webapp:
    build: ./webapp
    image: slashe/webapp
    ports:
      - "1000:80"
    restart: always