version: "3"
services:
  node:
    image: slashe/node:1.0.3
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "1000:8080"
  webapp:
    image: slashe/webapp:${SEILA}
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "2000:80"